Resources:
    securityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for cloudformation web server
        SecurityGroupIngress:
          -
            IpProtocol: tcp
            CidrIp: 0.0.0.0/0
            FromPort: 80
            ToPort: 80


    MyEC2Instance:
      Type: AWS::EC2::Instance
      Metadata:
        AWS::CloudFormation::Init:
          config:
            packages:
              yum:
                httpd: []
            services:
              sysvinit:
                httpd:
                  enabled: true
                  ensureRunning: true

      Properties:
        ImageId: ami-467ca739
        InstanceType: m4.large
        SecurityGroups:
        - !Ref securityGroup
        UserData:
          Fn::Base64:
            !Sub |
            #!/bin/bash -xe
            yum install -y aws-cfn-bootstrap
            /opt/bin/aws/cfn-init -s ${AWS::StackId} -r MyEC2Instance -v

    Output:
      MyEC2InstanceIPAddress:
        Value: !Sub ${MyEC2Instance.PublicIp}
